[build]
  base = "."
  publish = "."
  command = "npm install"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "NOTIFY_EMAIL,SMTP_HOST,SMTP_PASS,SMTP_PORT,SMTP_USER"
  SECRETS_SCAN_ENABLED = "false"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
